
// PRONTO


package br.com.senac.portfolio;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Thamiris da Silva Souza
 * @author Leila Jhenifer Nascimento de Aquino
 * 
 */



public class CalculoMedia extends javax.swing.JFrame {

    //Método para limpar os campos (caixas de texto)
    //private void -> construir um método (ação)
    //limpar -> nome do método
    private void limpar() {
        //fazer o método limpar as caixas de texto
        txt1.setText(null);
        txt2.setText(null);
        txt3.setText(null);
        txt4.setText(null);
        txtmedia.setText(null);
        }
    
    //Método para calcular a média das notas
    private void calcular() {
        //Criando um objeto para formatação do resultado
        //0.00 duas casas decimais / 0.0 uma casa decimal
        DecimalFormat formatador = new DecimalFormat("#0.0");

        //criando variaveis do tipo real
        float nota1,nota2,nota3,nota4,media;
        
        //entrada de dados
        //a linha abaixo captura o que foi digitado e armazena dados
        //.replace(",",".") troca a vírgula pelo ponto.
        nota1 = Float.parseFloat(txt1.getText().replace(",","."));
        nota2 = Float.parseFloat(txt2.getText().replace(",","."));
        nota3 = Float.parseFloat(txt3.getText().replace(",","."));
        nota4 = Float.parseFloat(txt4.getText().replace(",","."));
        
        //processamento:
        media = (nota1 + nota2 + nota3 + nota4)/4;
        
        //saída dos resultados
        //a linha abaixo exibe o resultado na media
        //Formatador é o objeto criado para formatar casas decimais
        txtmedia.setText("" + formatador.format(media));
        
        
        //estrutura condicional para determinar se o aluno está aprovado, reprovado ou de recuperação
        if (media < 2) {
        //criando uma caixa de diálogo para exibir a condição
        //JOptionPane.showMessageDialog = CRIAR UMA CAIXA DE DIÁLOGO.
        //null = TAMANHO PADRÃO.
        //"Texto"
        //"Título"
        //JOptionPane.ERROR_MESSAGE = ÍCONE PERSONALIZADO DE ERRO.
        JOptionPane.showMessageDialog(null,"REPROVADO","ATENÇÃO",JOptionPane.ERROR_MESSAGE);
        } 
        
        else if (media >=2 && media <5){
        JOptionPane.showMessageDialog(null,"RECUPERAÇÃO","ATENÇÃO",JOptionPane.WARNING_MESSAGE);
        }
        
        else 
            JOptionPane.showMessageDialog(null,"APROVADO","ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
        
    } 
    
    
    //___________________________________________________________________________________________________________
    
    
    /**
     * Creates new form CalculoMedia
     */
    public CalculoMedia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        media = new javax.swing.JLabel();
        nota2 = new javax.swing.JLabel();
        nota3 = new javax.swing.JLabel();
        nota1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        botaolimpar = new javax.swing.JButton();
        botaocalcular = new javax.swing.JButton();
        txtmedia = new javax.swing.JTextField();
        nota4 = new javax.swing.JLabel();
        txt4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        media.setText("Média:");

        nota2.setText("Nota 2:");

        nota3.setText("Nota 3:");

        nota1.setText("Nota 1:");

        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });

        txt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt3ActionPerformed(evt);
            }
        });

        botaolimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/portfolio/icones/borracha.png"))); // NOI18N
        botaolimpar.setToolTipText("Limpar");
        botaolimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaolimpar.setPreferredSize(new java.awt.Dimension(80, 80));
        botaolimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaolimparActionPerformed(evt);
            }
        });

        botaocalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/portfolio/icones/calculator.png"))); // NOI18N
        botaocalcular.setToolTipText("Calcular");
        botaocalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaocalcular.setPreferredSize(new java.awt.Dimension(50, 50));
        botaocalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaocalcularActionPerformed(evt);
            }
        });

        txtmedia.setEditable(false);
        txtmedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmediaActionPerformed(evt);
            }
        });

        nota4.setText("Nota 4:");

        txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaocalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(botaolimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(media, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(txtmedia, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(nota2)
                                        .addComponent(nota3)
                                        .addComponent(nota1))
                                    .addComponent(nota4))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt4)
                                    .addComponent(txt1)
                                    .addComponent(txt3)
                                    .addComponent(txt2, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))))))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(nota1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nota2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nota3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nota4)
                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(media, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaocalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(botaolimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt3ActionPerformed

    private void botaolimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaolimparActionPerformed
        //Executar o método limpar()
        limpar();
    }//GEN-LAST:event_botaolimparActionPerformed

    private void botaocalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaocalcularActionPerformed
        //Executando o método calcular()
        calcular();

    }//GEN-LAST:event_botaocalcularActionPerformed

    private void txtmediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmediaActionPerformed

    private void txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculoMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculoMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculoMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculoMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculoMedia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaocalcular;
    private javax.swing.JButton botaolimpar;
    private javax.swing.JLabel media;
    private javax.swing.JLabel nota1;
    private javax.swing.JLabel nota2;
    private javax.swing.JLabel nota3;
    private javax.swing.JLabel nota4;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txtmedia;
    // End of variables declaration//GEN-END:variables
}
