
//  -------------- PRONTO --------------//


package br.com.senac.portfolio;

/**
 *
 * @author Thamiris da Silva Souza
 * @author Leila Jhenifer Nascimento de Aquino
 * 
 */

public class Portfolio extends javax.swing.JFrame {
 
    /**
     * Creates new form Portfolio
     */
    
    public Portfolio() {
        initComponents();
    }   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    // Abaixo a criação dos botões para chamar os JFrames:
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calculadora = new javax.swing.JButton();
        dados = new javax.swing.JButton();
        alcool = new javax.swing.JButton();
        ppt = new javax.swing.JButton();
        cartas = new javax.swing.JButton();
        imc = new javax.swing.JButton();
        conversor = new javax.swing.JButton();
        media = new javax.swing.JButton();
        tabuada = new javax.swing.JButton();
        jogodavelha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PORTFÓLIO DE APLICATIVOS");
        setBackground(new java.awt.Color(255, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        calculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/portfolio/icones/calculator.png"))); // NOI18N
        calculadora.setToolTipText("Calculadora");
        calculadora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculadoraActionPerformed(evt);
            }
        });

        dados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/portfolio/icones/dado.png"))); // NOI18N
        dados.setToolTipText("Jogo de Dados");
        dados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dadosActionPerformed(evt);
            }
        });

        alcool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/portfolio/icones/gasolina.png"))); // NOI18N
        alcool.setToolTipText("Alcoól ou Gasolina");
        alcool.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alcool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alcoolActionPerformed(evt);
            }
        });

        ppt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/portfolio/icones/peace-sign.png"))); // NOI18N
        ppt.setToolTipText("Pedra-Papel-Tesoura");
        ppt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pptActionPerformed(evt);
            }
        });

        cartas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/portfolio/icones/cartas.png"))); // NOI18N
        cartas.setToolTipText("Jogo de Cartas");
        cartas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cartas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartasActionPerformed(evt);
            }
        });

        imc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/portfolio/icones/imc.png"))); // NOI18N
        imc.setToolTipText("Cálculo do IMC");
        imc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imcActionPerformed(evt);
            }
        });

        conversor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/portfolio/icones/money-flow.png"))); // NOI18N
        conversor.setToolTipText("Conversor de Dinheiro");
        conversor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        conversor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conversorActionPerformed(evt);
            }
        });

        media.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/portfolio/icones/school.png"))); // NOI18N
        media.setToolTipText("Cálculo da Média");
        media.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        media.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediaActionPerformed(evt);
            }
        });

        tabuada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/portfolio/icones/tabuada.png"))); // NOI18N
        tabuada.setToolTipText("Tabuada");
        tabuada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabuada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabuadaActionPerformed(evt);
            }
        });

        jogodavelha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/portfolio/icones/tic-tac-toe.png"))); // NOI18N
        jogodavelha.setToolTipText("Jogo da Velha");
        jogodavelha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jogodavelha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogodavelhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calculadora)
                    .addComponent(cartas)
                    .addComponent(dados)
                    .addComponent(alcool)
                    .addComponent(ppt))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jogodavelha)
                    .addComponent(tabuada)
                    .addComponent(media)
                    .addComponent(conversor)
                    .addComponent(imc))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calculadora)
                    .addComponent(imc))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cartas)
                    .addComponent(conversor))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dados)
                    .addComponent(media))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alcool)
                    .addComponent(tabuada))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ppt)
                    .addComponent(jogodavelha))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("Aplicativos");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void calculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculadoraActionPerformed
        new Calculadora().setVisible(true);    
    }//GEN-LAST:event_calculadoraActionPerformed

    private void cartasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartasActionPerformed
       new JogoCartas().setVisible(true);         
    }//GEN-LAST:event_cartasActionPerformed

    private void imcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imcActionPerformed
        new CalculoIMC().setVisible(true);        
    }//GEN-LAST:event_imcActionPerformed

    private void mediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediaActionPerformed
        new CalculoMedia().setVisible(true);      
    }//GEN-LAST:event_mediaActionPerformed

    private void conversorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conversorActionPerformed
        new ConversorDinheiro().setVisible(true);
    }//GEN-LAST:event_conversorActionPerformed

    private void dadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dadosActionPerformed
        new JogoDado().setVisible(true);
    }//GEN-LAST:event_dadosActionPerformed

    private void alcoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alcoolActionPerformed
        new AlcoolGasolina().setVisible(true);
    }//GEN-LAST:event_alcoolActionPerformed

    private void tabuadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabuadaActionPerformed
        new Tabuada().setVisible(true);
    }//GEN-LAST:event_tabuadaActionPerformed

    private void pptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pptActionPerformed
        new PedraPapelTesoura().setVisible(true);
    }//GEN-LAST:event_pptActionPerformed

    private void jogodavelhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogodavelhaActionPerformed
        new JogoDaVelha().setVisible(true);
    }//GEN-LAST:event_jogodavelhaActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Portfolio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Portfolio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Portfolio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Portfolio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Portfolio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alcool;
    private javax.swing.JButton calculadora;
    private javax.swing.JButton cartas;
    private javax.swing.JButton conversor;
    private javax.swing.JButton dados;
    private javax.swing.JButton imc;
    private javax.swing.JButton jogodavelha;
    private javax.swing.JButton media;
    private javax.swing.JButton ppt;
    private javax.swing.JButton tabuada;
    // End of variables declaration//GEN-END:variables
}